### ISSUE TITLE
POST fails

### ISSUE THREAD

**Issue by martin093** [fvalverd/AutoApi#2]
I run AutoApi as ```python -m auto_api``` and then I created an item inside the collection **groups** on the API **Fut**, like this:
```
POST /Fut/groups
Content-Type: application/json

{"field": ...}
```
The output was good:
```
{"id": ...}
```
But, when I did the same request changing the API to **fut** (expecting to use a different API) like this:
```
POST /fut/groups
Content-Type: application/json

{"field": ...}
```
I got the following error:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

**Comment by fvalverd** [comment]
You'r right, that happened because AutoApi implements an API as a database in MongoDB and there are some restrictions about naming a database, one says that [each database name is case-insensitive](https://docs.mongodb.com/manual/reference/limits#Database-Name-Case-Sensitivity), therefore when you tried to do a *POST* on the API *fut* MongoDB complained about it because *Fut* already  #exists.

After reading some conventions about to naming a database in MongoDB, **I think is better to store an API on lower-case and every API in AutoApi case-insensitive**. I [already fixed this](https://github.com/fvalverd/AutoApi/commit/72d5234cddef0255a7f54fb02f4dbcb7f3f5ffd9) (from v1.0.3).

I strongly recommend you to update AutoApi to the latest version, and only in your case change the name of the database in Mongo(https://stackoverflow.com/questions/9201832/how-do-you-rename-a-mongodb-database) from *Fut* to *fut*.
